USE [master]
ALTER DATABASE [GLASS4] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [GLASS4] FROM  DISK = N'\\den-q2s-sqlis\SQLBackup\SQLBackup\DEN-Q2S-SQL\GLASS4\GLASS4_2014-12-16_03_49_47.full'
    WITH  FILE = 1,
    MOVE N'GLASS4' TO N'I:\DB\MSSQL\GLASS4.mdf',
    MOVE N'INDEXES' TO N'I:\DB\MSSQL\GLASS4_INDEXES.mdf',
    MOVE N'CACHE' TO N'I:\DB\MSSQL\GLASS4_CACHE.mdf',
    MOVE N'READONLY' TO N'I:\DB\MSSQL\GLASS4_READONLY.mdf',
    NOUNLOAD,
    REPLACE,
    STATS = 5
ALTER DATABASE [GLASS4] SET MULTI_USER

GO


